/**
 * AgentCommerceAdapter types.
 *
 * ⚠️ This directory (core/) is FRAMEWORK-FREE: no Next/Drizzle/Stripe.
 * It is the candidate for extraction as the `@openticket/agent-commerce-adapter`
 * package (architecture-review §2). Dependencies come in through core/ports.ts.
 *
 * Incorporates the 3 fixes from protocol-audit §2:
 *  - `mode`: ACP is a stateful session (create/update/complete), MCP is one-shot.
 *  - AUTHORIZATION axis separated from the SETTLEMENT axis (AP2 is an overlay, not a parallel rail).
 *  - Two capture modes: `stripe_hosted` (v1) and `stripe_inline_spt`
 *    (planned for ACP conformance, NOT implemented in F0/F1).
 */

export type Rail = "web" | "acp" | "mcp" | "ap2" | "x402" | "mpp";

export type AdapterMode = "one_shot" | "session";

/** Authorization axis: how spend permission is validated. */
export type AuthorizationScheme = "none" | "spend_limit" | "ap2_mandate";

/** Settlement axis: how the money moves. */
export type SettlementScheme =
  | "stripe_hosted" // v1: hosted Checkout link + webhook (async)
  | "stripe_inline_spt" // ACP: inline Shared Payment Token on /complete (F2, not implemented)
  | "x402" // onchain stablecoin (later phase)
  | "mpp"; // fiat-over-402 via Stripe (stub, redundant with x402)

/** Money is ALWAYS in minor units (cents) + ISO 4217. Never floats. */
export interface Money {
  amountMinor: number;
  currency: string;
}

export interface Buyer {
  email: string;
  name?: string;
  /** user id in the agent's client */
  externalRef?: string;
}

/** Normalized purchase intent — what resolveIntent of any rail produces. */
export interface PurchaseIntent {
  idempotencyKey: string;
  eventId: string;
  ticketTypeId: string;
  quantity: number;
  buyer: Buyer;
  rail: Rail;
  /**
   * Declared spend cap. With authorization="spend_limit" it is REQUIRED.
   * Honesty NOTE (architecture-review P5): without a signed AP2 mandate this is
   * self-declared by the agent — it documents intent, it is not a security control.
   */
  spendLimit?: Money;
  /** Opaque to the core; understood by the RailAdapter (AP2 mandate, 402 receipt, SPT…). */
  paymentContext?: unknown;
}

export type OrderStatus =
  | "pending_payment"
  | "confirmed"
  | "expired"
  | "cancelled"
  | "refunded";

export type EventStatus = "draft" | "published" | "sold_out" | "cancelled";
export type TicketTypeStatus = "active" | "hidden" | "sold_out";
export type TicketStatus = "valid" | "used" | "void";

export interface Order {
  id: string;
  eventId: string;
  ticketTypeId: string;
  quantity: number;
  buyerEmail: string;
  buyerName: string | null;
  rail: Rail;
  boughtByAgent: boolean;
  status: OrderStatus;
  amountMinor: number;
  platformFeeMinor: number;
  currency: string;
  spendLimitMinor: number | null;
  mandateRef: string | null;
  idempotencyKey: string;
  checkoutUrl: string | null;
  stripeCheckoutSessionId: string | null;
  stripePaymentIntentId: string | null;
  expiresAt: Date | null;
  createdAt: Date;
  confirmedAt: Date | null;
}

export interface EventRecord {
  id: string;
  organizerId: string;
  title: string;
  description: string;
  slug: string;
  venue: string | null;
  startsAt: Date;
  endsAt: Date | null;
  timezone: string;
  currency: string;
  status: EventStatus;
}

export interface TicketTypeRecord {
  id: string;
  eventId: string;
  name: string;
  priceMinor: number;
  quota: number;
  issued: number;
  reserved: number;
  status: TicketTypeStatus;
}

export interface TicketRecord {
  id: string;
  code: string;
  status: TicketStatus;
}

/** Ticket seed generated by the core; the store persists it atomically. */
export interface TicketSeed {
  id: string;
  code: string;
}

/** Normalized pipeline result; each rail re-formats it in formatResult. */
export interface PurchaseResult {
  status: OrderStatus;
  /** true if this response comes from an already-processed idempotency key */
  duplicate: boolean;
  orderId: string;
  checkoutUrl: string | null;
  expiresAt: Date | null;
  amount: Money;
  platformFee: Money;
  event: { id: string; title: string; startsAt: Date; venue: string | null };
  tickets: TicketRecord[];
  /** relative path to the on-demand .ics (only when status=confirmed) */
  icsPath: string | null;
}

/**
 * One-shot adapter (MCP, web): one request → one result.
 * Only covers what varies per rail; the pipeline belongs to PurchaseCore.
 */
export interface RailAdapter<Raw = unknown, Result = unknown> {
  readonly rail: Rail;
  readonly mode: AdapterMode;
  readonly authorization: AuthorizationScheme;
  readonly settlement: SettlementScheme;
  /** Translates the raw protocol request into a normalized PurchaseIntent.
   *  MUST validate with Zod (trust boundary) and throw invalid_intent if it fails. */
  resolveIntent(raw: Raw): PurchaseIntent;
  /** Formats the confirmation in the shape THAT rail expects to return. */
  formatResult(result: PurchaseResult): Result;
}

/**
 * Contract for rails with a stateful session (ACP: create/update/complete).
 * Declared in F0 so the core does not break when ACP lands (F2);
 * the session adapter composes the same PurchaseCore primitives
 * (reserve → authorize → capture → fulfill) spread across requests.
 * NOT implemented in F0/F1.
 */
export interface SessionRailAdapter<Raw = unknown, Result = unknown> {
  readonly rail: Rail;
  readonly mode: "session";
  readonly authorization: AuthorizationScheme;
  readonly settlement: SettlementScheme;
  createSession(raw: Raw): Promise<Result>;
  updateSession(sessionId: string, raw: Raw): Promise<Result>;
  getSession(sessionId: string): Promise<Result>;
  completeSession(sessionId: string, raw: Raw): Promise<Result>;
  cancelSession(sessionId: string): Promise<Result>;
}
